version: "3.3"

volumes:
  mysql:
  project:
  results:
  secrets:

services:
  traefik:
    image: "traefik:2.3@sha256:3f5c5a46ccff636a9e726961f123638bd6854191040072d860fc15bbcee3e184"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  mysql:
    container_name: "phath_mysql"
    build: 
      context: images/mysql
    ports:
      - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"

  makeproject:
    container_name: "phath_mkproject"
    build: 
      context: images/makeproject
      args:
        - BOINC_USER
        - PROJECT_ROOT
    depends_on:
      - mysql
    volumes:
      - "project:$PROJECT_ROOT.dst"
      - "secrets:/run/secrets"
    hostname: makeproject
    environment:
      - URL_BASE
      - PROJECT

  apache:
    container_name: "phath_boinc"
    build: 
      context: images/apache
      args:
        - BOINC_USER
        - PROJECT_ROOT
    hostname: $PROJECT
    depends_on:
      - mysql
    volumes: 
      - "project:$PROJECT_ROOT"
      - "results:/results"
      - "secrets:/run/secrets"
      - "/dev/null:/run/secrets/keys/code_sign_private"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.home.addprefix.prefix=/minecrafthome"
    tty: true
    environment:
      - URL_BASE
      - PROJECT
